services:
  fluent-bit:
    image: fluent/fluent-bit:latest
    container_name: fluent-bit
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
      - ../logs:/logs
    ports:
      - "2020:2020"
      - "2021:2021"
    restart: always

  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - ./loki/loki.yml:/etc/loki/loki.yml
      - ./loki/storage:/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki.yml -config.expand-env=true
    restart: always
    env_file:
      - env/.env

  prometheus:
    image: prom/prometheus:v2.50.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

#volumes:
#  loki_data:
#  fluentbit_logs:
#  grafana_data: