services:
  fluent-bit:
    image: fluent/fluent-bit:3.2.3
    container_name: fluent-bit
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
      - ../logs:/logs
    ports:
      - "2020:2020"
      - "2021:2021"
    restart: always

  loki:
    image: grafana/loki:3.3.2
    container_name: loki
    volumes:
      - ./loki/loki.yml:/etc/loki/local-config.yml
      - ./loki/data:/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yml -config.expand-env=true
    restart: always
    env_file:
      - env/.env

  prometheus:
    image: prom/prometheus:v2.50.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/password.txt:/etc/prometheus/password.txt
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus

  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/data:/var/lib/grafana