name: Deploy to Amazon EC2

on:
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      # 기본 체크아웃
      - name: Checkout
        uses: actions/checkout@v4

      ## properties 파일 세팅
      - name: Setup application.properties
        run: |
          mkdir -p ./src/main/resources &&
          touch ./src/main/resources/application.properties &&
          echo "${{ secrets.DEV_PROPERTIES }}" > ./src/main/resources/application.properties
        shell: bash

      ## deploy.sh 생성
      - name: Setup deploy.sh
        run: |
          touch ./deploy.sh &&
          echo "${{ secrets.DEV_DEPLOY_SH_SCRIPT }}" > ./deploy.sh
        shell: bash

      # JDK 21 세팅
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # Gradlew 실행 허용
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup Gradle 8.6
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.6"

      # Gradle build (Test 제외)
      - name: Execute Gradle build
        run: ./gradlew build -x test

      - name: Deliver Files
        uses: appleboy/scp-action@master
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          port: ${{ secrets.EC2_SSH_PORT }}
          source: "build/libs/jigumulmi-0.0.1-SNAPSHOT.jar,deploy.sh"
          target: /home/ubuntu/dev

      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: ${{ secrets.EC2_SCRIPT }}