name: Unit Test with Gradle

on:
  pull_request:
    branches: [ dev ]

permissions:
  checks: write

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      # 기본 체크아웃
      - name: Checkout
        uses: actions/checkout@v4

      ## properties 파일 세팅
      - name: Setup application.properties
        env:
          MAIN_PROPERTY_DIR: ./src/main/resources
          MAIN_PROPERTY_FILE: application.properties
          TEST_PROPERTY_DIR: ./src/test/resources
          TEST_PROPERTY_FILE: application-default.properties
        run: |
          mkdir -p $MAIN_PROPERTY_DIR $TEST_PROPERTY_DIR &&
          touch $MAIN_PROPERTY_DIR/$MAIN_PROPERTY_FILE &&
          touch $TEST_PROPERTY_DIR/$TEST_PROPERTY_FILE &&
          echo "${{ secrets.DEV_PROPERTIES }}" > $MAIN_PROPERTY_DIR/$MAIN_PROPERTY_FILE &&
          echo "${{ secrets.TEST_PROPERTIES }}" > $TEST_PROPERTY_DIR/$TEST_PROPERTY_FILE
        shell: bash

      # JDK 21 세팅
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # Gradlew 실행 허용
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      # Gradle test 실행
      - name: Test with Gradle
        run: ./gradlew --info test

      # 테스트 후 Result 출력
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: ${{ always() }}  # 테스트 실패해도 출력
        with:
          files: build/test-results/**/*.xml
